services:
  frp-client:
    image: "registry.cn-shanghai.aliyuncs.com/iproute/frp:0.61.1"
    container_name: "frp-client"
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./client.toml:/opt/frp/client.toml"
      - "./log:/opt/frp/log"
    working_dir: "/opt/frp"
    restart: "always"
    command:
      - "./frpc"
      - "-c"
      - "client.toml"
