bindPort = 7000

log.to = "./log/frps.log"
log.level = "info"
log.maxDays = 3

auth.method = "token"
auth.token = "abc"

# 默认为 127.0.0.1，如果需要公网访问，需要修改为 0.0.0.0。
webServer.addr = "0.0.0.0"
webServer.port = 7500
# dashboard 用户名密码，可选，默认为空
webServer.user = "admin"
webServer.password = "admin"
